# Generated by Django 5.2.17 on 2026-10-04 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommateprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='gender_preference',
            field=models.CharField(choices=[('male', 'Looking for Male'), ('female', 'Looking for Female'), ('any', 'Any Gender')], default='any', max_length=10),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
