# Generated by Django 5.2.17 on 2026-09-26 09:59

import django.core.validators
import django.db.models.deletion
import hostels.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('HOSTEL', 'Hostel'), ('PG', 'PG'), ('RESIDENCE', 'Student Residence'), ('APARTMENT', 'Shared Apartment')], default='HOSTEL', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gender_allowed', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=10)),
                ('food_available', models.BooleanField(default=False)),
                ('food_type', models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('BOTH', 'Veg & Non-Veg')], max_length=10)),
                ('breakfast_included', models.BooleanField(default=False)),
                ('lunch_included', models.BooleanField(default=False)),
                ('dinner_included', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('common_room', models.BooleanField(default=False)),
                ('study_room', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('housekeeping', models.BooleanField(default=False)),
                ('hot_water', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hostels.models.hostel_image_upload_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hostels.hostel')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double Sharing'), ('TRIPLE', 'Triple Sharing'), ('FOUR', 'Four Sharing')], max_length=10)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_beds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_beds', models.PositiveIntegerField(default=0)),
                ('bathroom_type', models.CharField(choices=[('ATTACHED', 'Attached'), ('SHARED', 'Shared')], default='SHARED', max_length=10)),
                ('furnishing', models.CharField(choices=[('FULLY', 'Fully Furnished'), ('SEMI', 'Semi Furnished'), ('UNFURNISHED', 'Unfurnished')], default='SEMI', max_length=15)),
                ('ac_available', models.BooleanField(default=False)),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('room_size', models.CharField(blank=True, help_text='e.g. 120 sq.ft.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('FULL', 'Full')], default='AVAILABLE', editable=False, max_length=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.hostel')),
            ],
            options={
                'ordering': ['rent'],
            },
        ),
    ]
