# Generated by Django 5.2.17 on 2026-10-04 11:27

import hostels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_hostelimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to=hostels.models.hostel_image_upload_path),
        ),
    ]
